### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by NekoTony** [teamreflex/discord-oauth#10]
How would i use this to make a sign in? I ran composer successfully into but what do i next? how would i make a sign in?

**Comment by NekoTony** [comment]
Like do u have a doc i could look at?

**Comment by shibdib** [comment]
If you can't even find the doc I don't think this is gonna work for you

**Comment by NekoTony** [comment]
Sorry, but i don't recall seeing a page called docs nor does the wiki work, sooo...
