### ISSUE TITLE
Not compatible with 2.0 version of league/oauth2-client

### ISSUE THREAD

**Issue by MadMikeyB** [teamreflex/discord-oauth#11]
Because in composer.json you list the following:

`"league/oauth2-client": "^1.3",`

Upon upgrading to league/oauth2-client 2.0, I can no longer use this version. Composer spits out an error.

Could you confirm whether this is compatible with league/oauth2-client 2.0 ? All the official league/ providers now require 2.0, so I cannot downgrade. 

Thanks!

**Comment by ImJustToNy** [comment]
Please ;(

**Comment by Skullfox** [comment]
^

**Comment by GRX** [comment]
Is this solved by any chance? I keep googling for sollutions to my problems but every damn tutorial or page related to an Discord PHP OAUTH API keeps linking to this project.

I can't seem to install via composer, and when I download it and unpack it in my pub_html it keeps returning errors about missing classes.

**Comment by Skullfox** [comment]
Sadly not

**Comment by danielpearceofficial** [comment]
Please fix this I can't figure any way to download it now :(

**Comment by MadMikeyB** [comment]
Use this newer package: https://github.com/wohali/oauth2-discord-new

Seems this current one is abandonware.
