### ISSUE TITLE
Class 'Discord\OAuth\Discord' not found

### ISSUE THREAD

**Issue by puwa-puwa** [teamreflex/discord-oauth#13]
code:
$provider = new Discord\OAuth\Discord([
        'clientId'     => 'CLIENTID',
        'clientSecret' => 'CLIENTSECRET',
        'redirectUri'  => 'REDIRECTURI'
`]);
result:
![image](https://cloud.githubusercontent.com/assets/6093953/24722548/6cb1d088-1a44-11e7-81ef-f6e2989235fb.png)

**Comment by jaspervdm** [comment]
You should actually load the class, either with the composer autoloader (`vendor/autoload.php`) or you could write your own.

**Comment by stevemulligan** [comment]
Something like this:

`include join(DIRECTORY_SEPARATOR, [__DIR__, 'vendor', 'autoload.php']);`

**Comment by puwa-puwa** [comment]
it works, thanks
